import java.util.Scanner;

public class Exception4
{
    public static void main(String[] args) 
    {
        try
        {
            //code
        }
        catch(ArrayIndexOutOfBoundsException obj)
        {}
        catch(ArithmeticException obj)
        {}
        catch(Exception obj)
        {}
        finally
        {
            System.out.println("Inside finally block");
        }
    }
}                                              
